export const PREMIUM_PLAYER_QA = {
  idleLock: 'player-premium-idle-lock',
  idleFrames: ['player-premium-idle-01', 'player-premium-idle-02', 'player-premium-idle-03', 'player-premium-idle-04'],
  walkFrames: ['player-premium-walk-01', 'player-premium-walk-02', 'player-premium-walk-03', 'player-premium-walk-04', 'player-premium-walk-05', 'player-premium-walk-06'],
  runFrames: ['player-premium-run-01', 'player-premium-run-02', 'player-premium-run-03', 'player-premium-run-04', 'player-premium-run-05', 'player-premium-run-06', 'player-premium-run-07', 'player-premium-run-08'],
  jumpFrames: ['player-premium-jump-01', 'player-premium-jump-02', 'player-premium-jump-03', 'player-premium-jump-04'],
  fallFrames: ['player-premium-fall-01', 'player-premium-fall-02'],
  wingFlapFrames: ['player-premium-wing-flap-01', 'player-premium-wing-flap-02', 'player-premium-wing-flap-03', 'player-premium-wing-flap-04'],
  glideFrames: ['player-premium-glide-01', 'player-premium-glide-02'],
  wallClingFrames: ['player-premium-wall-cling-01'],
  wallClimbFrames: ['player-premium-wall-climb-01', 'player-premium-wall-climb-02', 'player-premium-wall-climb-03', 'player-premium-wall-climb-04'],
  wallJumpFrames: ['player-premium-wall-jump-01', 'player-premium-wall-jump-02', 'player-premium-wall-jump-03', 'player-premium-wall-jump-04'],
  dodgeFrames: ['player-premium-dodge-01', 'player-premium-dodge-02', 'player-premium-dodge-03', 'player-premium-dodge-04', 'player-premium-dodge-05'],
  hurtFrames: ['player-premium-hurt-01', 'player-premium-hurt-02', 'player-premium-hurt-03'],
  deathFrames: ['player-premium-death-01', 'player-premium-death-02', 'player-premium-death-03', 'player-premium-death-04', 'player-premium-death-05', 'player-premium-death-06'],
  respawnFrames: ['player-premium-respawn-01', 'player-premium-respawn-02', 'player-premium-respawn-03', 'player-premium-respawn-04'],
} as const;

export const PREMIUM_PLAYER_QA_ASSET_PATHS: Record<string, string> = {
  [PREMIUM_PLAYER_QA.idleLock]: 'assets/player/premium-v1/roach_side_right_idle_lock_256.png',
  [PREMIUM_PLAYER_QA.idleFrames[0]]: 'assets/player/premium-v1/frames/idle/roach_idle_01.png',
  [PREMIUM_PLAYER_QA.idleFrames[1]]: 'assets/player/premium-v1/frames/idle/roach_idle_02.png',
  [PREMIUM_PLAYER_QA.idleFrames[2]]: 'assets/player/premium-v1/frames/idle/roach_idle_03.png',
  [PREMIUM_PLAYER_QA.idleFrames[3]]: 'assets/player/premium-v1/frames/idle/roach_idle_04.png',
  [PREMIUM_PLAYER_QA.walkFrames[0]]: 'assets/player/premium-v1/frames/walk/roach_walk_01.png',
  [PREMIUM_PLAYER_QA.walkFrames[1]]: 'assets/player/premium-v1/frames/walk/roach_walk_02.png',
  [PREMIUM_PLAYER_QA.walkFrames[2]]: 'assets/player/premium-v1/frames/walk/roach_walk_03.png',
  [PREMIUM_PLAYER_QA.walkFrames[3]]: 'assets/player/premium-v1/frames/walk/roach_walk_04.png',
  [PREMIUM_PLAYER_QA.walkFrames[4]]: 'assets/player/premium-v1/frames/walk/roach_walk_05.png',
  [PREMIUM_PLAYER_QA.walkFrames[5]]: 'assets/player/premium-v1/frames/walk/roach_walk_06.png',
  [PREMIUM_PLAYER_QA.runFrames[0]]: 'assets/player/premium-v1/frames/run/roach_run_01.png',
  [PREMIUM_PLAYER_QA.runFrames[1]]: 'assets/player/premium-v1/frames/run/roach_run_02.png',
  [PREMIUM_PLAYER_QA.runFrames[2]]: 'assets/player/premium-v1/frames/run/roach_run_03.png',
  [PREMIUM_PLAYER_QA.runFrames[3]]: 'assets/player/premium-v1/frames/run/roach_run_04.png',
  [PREMIUM_PLAYER_QA.runFrames[4]]: 'assets/player/premium-v1/frames/run/roach_run_05.png',
  [PREMIUM_PLAYER_QA.runFrames[5]]: 'assets/player/premium-v1/frames/run/roach_run_06.png',
  [PREMIUM_PLAYER_QA.runFrames[6]]: 'assets/player/premium-v1/frames/run/roach_run_07.png',
  [PREMIUM_PLAYER_QA.runFrames[7]]: 'assets/player/premium-v1/frames/run/roach_run_08.png',
  [PREMIUM_PLAYER_QA.jumpFrames[0]]: 'assets/player/premium-v1/frames/jump/roach_jump_01.png',
  [PREMIUM_PLAYER_QA.jumpFrames[1]]: 'assets/player/premium-v1/frames/jump/roach_jump_02.png',
  [PREMIUM_PLAYER_QA.jumpFrames[2]]: 'assets/player/premium-v1/frames/jump/roach_jump_03.png',
  [PREMIUM_PLAYER_QA.jumpFrames[3]]: 'assets/player/premium-v1/frames/jump/roach_jump_04.png',
  [PREMIUM_PLAYER_QA.fallFrames[0]]: 'assets/player/premium-v1/frames/fall/roach_fall_01.png',
  [PREMIUM_PLAYER_QA.fallFrames[1]]: 'assets/player/premium-v1/frames/fall/roach_fall_02.png',
  [PREMIUM_PLAYER_QA.wingFlapFrames[0]]: 'assets/player/premium-v1/frames/wing_flap/roach_wing_flap_01.png',
  [PREMIUM_PLAYER_QA.wingFlapFrames[1]]: 'assets/player/premium-v1/frames/wing_flap/roach_wing_flap_02.png',
  [PREMIUM_PLAYER_QA.wingFlapFrames[2]]: 'assets/player/premium-v1/frames/wing_flap/roach_wing_flap_03.png',
  [PREMIUM_PLAYER_QA.wingFlapFrames[3]]: 'assets/player/premium-v1/frames/wing_flap/roach_wing_flap_04.png',
  [PREMIUM_PLAYER_QA.glideFrames[0]]: 'assets/player/premium-v1/frames/glide/roach_glide_01.png',
  [PREMIUM_PLAYER_QA.glideFrames[1]]: 'assets/player/premium-v1/frames/glide/roach_glide_02.png',
  [PREMIUM_PLAYER_QA.wallClingFrames[0]]: 'assets/player/premium-v1/frames/wall_cling/roach_wall_cling_01.png',
  [PREMIUM_PLAYER_QA.wallClimbFrames[0]]: 'assets/player/premium-v1/frames/wall_climb/roach_wall_climb_01.png',
  [PREMIUM_PLAYER_QA.wallClimbFrames[1]]: 'assets/player/premium-v1/frames/wall_climb/roach_wall_climb_02.png',
  [PREMIUM_PLAYER_QA.wallClimbFrames[2]]: 'assets/player/premium-v1/frames/wall_climb/roach_wall_climb_03.png',
  [PREMIUM_PLAYER_QA.wallClimbFrames[3]]: 'assets/player/premium-v1/frames/wall_climb/roach_wall_climb_04.png',
  [PREMIUM_PLAYER_QA.wallJumpFrames[0]]: 'assets/player/premium-v1/frames/wall_jump/roach_wall_jump_01.png',
  [PREMIUM_PLAYER_QA.wallJumpFrames[1]]: 'assets/player/premium-v1/frames/wall_jump/roach_wall_jump_02.png',
  [PREMIUM_PLAYER_QA.wallJumpFrames[2]]: 'assets/player/premium-v1/frames/wall_jump/roach_wall_jump_03.png',
  [PREMIUM_PLAYER_QA.wallJumpFrames[3]]: 'assets/player/premium-v1/frames/wall_jump/roach_wall_jump_04.png',
  [PREMIUM_PLAYER_QA.dodgeFrames[0]]: 'assets/player/premium-v1/frames/dodge/roach_dodge_01.png',
  [PREMIUM_PLAYER_QA.dodgeFrames[1]]: 'assets/player/premium-v1/frames/dodge/roach_dodge_02.png',
  [PREMIUM_PLAYER_QA.dodgeFrames[2]]: 'assets/player/premium-v1/frames/dodge/roach_dodge_03.png',
  [PREMIUM_PLAYER_QA.dodgeFrames[3]]: 'assets/player/premium-v1/frames/dodge/roach_dodge_04.png',
  [PREMIUM_PLAYER_QA.dodgeFrames[4]]: 'assets/player/premium-v1/frames/dodge/roach_dodge_05.png',
  [PREMIUM_PLAYER_QA.hurtFrames[0]]: 'assets/player/premium-v1/frames/hurt/roach_hurt_01.png',
  [PREMIUM_PLAYER_QA.hurtFrames[1]]: 'assets/player/premium-v1/frames/hurt/roach_hurt_02.png',
  [PREMIUM_PLAYER_QA.hurtFrames[2]]: 'assets/player/premium-v1/frames/hurt/roach_hurt_03.png',
  [PREMIUM_PLAYER_QA.deathFrames[0]]: 'assets/player/premium-v1/frames/death/roach_death_01.png',
  [PREMIUM_PLAYER_QA.deathFrames[1]]: 'assets/player/premium-v1/frames/death/roach_death_02.png',
  [PREMIUM_PLAYER_QA.deathFrames[2]]: 'assets/player/premium-v1/frames/death/roach_death_03.png',
  [PREMIUM_PLAYER_QA.deathFrames[3]]: 'assets/player/premium-v1/frames/death/roach_death_04.png',
  [PREMIUM_PLAYER_QA.deathFrames[4]]: 'assets/player/premium-v1/frames/death/roach_death_05.png',
  [PREMIUM_PLAYER_QA.deathFrames[5]]: 'assets/player/premium-v1/frames/death/roach_death_06.png',
  [PREMIUM_PLAYER_QA.respawnFrames[0]]: 'assets/player/premium-v1/frames/respawn/roach_respawn_01.png',
  [PREMIUM_PLAYER_QA.respawnFrames[1]]: 'assets/player/premium-v1/frames/respawn/roach_respawn_02.png',
  [PREMIUM_PLAYER_QA.respawnFrames[2]]: 'assets/player/premium-v1/frames/respawn/roach_respawn_03.png',
  [PREMIUM_PLAYER_QA.respawnFrames[3]]: 'assets/player/premium-v1/frames/respawn/roach_respawn_04.png',
};

export const HD_PLAYER_BENCHMARK = {
  idle: 'player-hd-master',
  wing: 'player-hd-wing',
  wall: 'player-hd-wall',
} as const;

export const HD_PLAYER_ASSET_PATHS: Record<string, string> = {
  [HD_PLAYER_BENCHMARK.idle]: 'assets/player/hd-v2/roach_master_hd_v1_1024.png',
  [HD_PLAYER_BENCHMARK.wing]: 'assets/player/hd-v2/roach_wing_hd_v1_1024.png',
  [HD_PLAYER_BENCHMARK.wall]: 'assets/player/hd-v2/roach_wall_hd_v1_1024.png',
};

export const PLAYER_FRAMES = {
  idle: ['player-idle-01', 'player-idle-02', 'player-idle-03', 'player-idle-04'],
  walk: ['player-walk-01', 'player-walk-02', 'player-walk-03', 'player-walk-04', 'player-walk-05', 'player-walk-06'],
  run: ['player-run-01', 'player-run-02', 'player-run-03', 'player-run-04', 'player-run-05', 'player-run-06', 'player-run-07', 'player-run-08'],
  jump: ['player-jump-01', 'player-jump-02', 'player-jump-03', 'player-jump-04'],
  fall: ['player-fall-01', 'player-fall-02'],
  wallClimb: ['player-wall-climb-01', 'player-wall-climb-02', 'player-wall-climb-03', 'player-wall-climb-04'],
  dodge: ['player-dodge-01', 'player-dodge-02', 'player-dodge-03', 'player-dodge-04', 'player-dodge-05'],
  hurt: ['player-hurt-01', 'player-hurt-02', 'player-hurt-03'],
  death: ['player-death-01', 'player-death-02', 'player-death-03', 'player-death-04', 'player-death-05', 'player-death-06'],
} as const;

export const PLAYER_ASSET_PATHS: Record<string, string> = {
  'player-idle-01': 'assets/player/idle_01.png',
  'player-idle-02': 'assets/player/idle_02.png',
  'player-idle-03': 'assets/player/idle_03.png',
  'player-idle-04': 'assets/player/idle_04.png',
  'player-walk-01': 'assets/player/walk_01.png',
  'player-walk-02': 'assets/player/walk_02.png',
  'player-walk-03': 'assets/player/walk_03.png',
  'player-walk-04': 'assets/player/walk_04.png',
  'player-walk-05': 'assets/player/walk_05.png',
  'player-walk-06': 'assets/player/walk_06.png',
  'player-run-01': 'assets/player/run_01.png',
  'player-run-02': 'assets/player/run_02.png',
  'player-run-03': 'assets/player/run_03.png',
  'player-run-04': 'assets/player/run_04.png',
  'player-run-05': 'assets/player/run_05.png',
  'player-run-06': 'assets/player/run_06.png',
  'player-run-07': 'assets/player/run_07.png',
  'player-run-08': 'assets/player/run_08.png',
  'player-jump-01': 'assets/player/jump_01.png',
  'player-jump-02': 'assets/player/jump_02.png',
  'player-jump-03': 'assets/player/jump_03.png',
  'player-jump-04': 'assets/player/jump_04.png',
  'player-fall-01': 'assets/player/fall_01.png',
  'player-fall-02': 'assets/player/fall_02.png',
  'player-wall-climb-01': 'assets/player/wall_climb_01.png',
  'player-wall-climb-02': 'assets/player/wall_climb_02.png',
  'player-wall-climb-03': 'assets/player/wall_climb_03.png',
  'player-wall-climb-04': 'assets/player/wall_climb_04.png',
  'player-dodge-01': 'assets/player/dodge_01.png',
  'player-dodge-02': 'assets/player/dodge_02.png',
  'player-dodge-03': 'assets/player/dodge_03.png',
  'player-dodge-04': 'assets/player/dodge_04.png',
  'player-dodge-05': 'assets/player/dodge_05.png',
  'player-hurt-01': 'assets/player/hurt_01.png',
  'player-hurt-02': 'assets/player/hurt_02.png',
  'player-hurt-03': 'assets/player/hurt_03.png',
  'player-death-01': 'assets/player/death_01.png',
  'player-death-02': 'assets/player/death_02.png',
  'player-death-03': 'assets/player/death_03.png',
  'player-death-04': 'assets/player/death_04.png',
  'player-death-05': 'assets/player/death_05.png',
  'player-death-06': 'assets/player/death_06.png',
};
